/**
 * CERTIFICATES & TRAINING COURSES GALLERY DATASTORE
 * Official Certificates sorted by Date with Categories, PDF & High-Res Image Previews
 */

const CERTIFICATES_CATEGORIES = [
  { id: 'all', name: 'جميع الشهادات', icon: 'fa-award' },
  { id: 'academic', name: 'الشهادات الأكاديمية والتأهيلية', icon: 'fa-graduation-cap' },
  { id: 'gis', name: 'نظم المعلومات الجغرافية Esri & ArcFM', icon: 'fa-map-location-dot' },
  { id: 'scada', name: 'أنظمة التحكم والسكادا SCADA & ADMS', icon: 'fa-bolt' },
  { id: 'fortinet', name: 'الأمن السيبراني والشبكات Fortinet', icon: 'fa-shield-halved' },
  { id: 'web', name: 'تطوير الويب وإدارة البيانات', icon: 'fa-code' }
];

const CERTIFICATES_DATA = [
  {
    id: 'cert-g',
    titleAr: 'شهادة الاعتماد والتأهيل المهني المتخصص',
    titleEn: 'Official Graduation & Professional Diploma Certificate',
    issuer: 'Official Academic Institution',
    category: 'academic',
    categoryAr: 'أكاديمي وتأهيلي',
    date: '2026-06-16',
    year: '2026',
    pdfUrl: './certs/G.pdf',
    imageUrl: './certs/images/G.png',
    badgeClass: 'badge-gold',
    description: 'شهادة الاعتماد والتأهيل الرسمي المتخصص في الهندسة ونظم المعلومات والتطبيقات الذكية.'
  },
  {
    id: 'cert-building-geodatabases',
    titleAr: 'بناء وتصميم قواعد البيانات الجغرافية (Building Geodatabases)',
    titleEn: 'Building Geodatabases - Esri Certified Training',
    issuer: 'Esri (Environmental Systems Research Institute)',
    category: 'gis',
    categoryAr: 'نظم معلومات جغرافية',
    date: '2025-02-06',
    year: '2025',
    pdfUrl: './certs/BuildingGeoDataBases.pdf',
    imageUrl: './certs/images/BuildingGeoDataBases.png',
    badgeClass: 'badge-blue',
    description: 'تصميم وبناء قواعد البيانات الجغرافية Geodatabases وحرية ربط الطبقات والمعالم بالتطبيقات الهندسية.'
  },
  {
    id: 'cert-deploy-maintain-multiuser-geodatabase',
    titleAr: 'نشر وصيانة قواعد البيانات الجغرافية متعددة المستخدمين',
    titleEn: 'Deploying & Maintaining a Multiuser Geodatabase',
    issuer: 'Esri Certified Training',
    category: 'gis',
    categoryAr: 'نظم معلومات جغرافية',
    date: '2025-02-05',
    year: '2025',
    pdfUrl: './certs/Deploy&MaintainMultiuserGeodatabase.pdf',
    imageUrl: './certs/images/Deploy_MaintainMultiuserGeodatabase.png',
    badgeClass: 'badge-blue',
    description: 'إدارة السيرفرات وقواعد البيانات الجغرافية للمؤسسات Enterprise Geodatabases وإتاحة الصلاحيات لفرق العمل.'
  },
  {
    id: 'cert-distributing-geodatabase-replication',
    titleAr: 'توزيع البيانات باستخدام التكرار المتزامن للقواعد الجغرافية',
    titleEn: 'Distributing Data Using Geodatabase Replication',
    issuer: 'Esri Certified Training',
    category: 'gis',
    categoryAr: 'نظم معلومات جغرافية',
    date: '2025-02-04',
    year: '2025',
    pdfUrl: './certs/DistributingDataUsingGeodatabaseReplication.pdf',
    imageUrl: './certs/images/DistributingDataUsingGeodatabaseReplication.png',
    badgeClass: 'badge-blue',
    description: 'مزامنة وتكرار البيانات الجغرافية بين الفروع وتحديث التعديلات الميدانية تلقائياً عبر Geodatabase Replication.'
  },
  {
    id: 'cert-editing-data-arcgis-desktop',
    titleAr: 'تحرير وتحديث البيانات في ArcGIS Desktop',
    titleEn: 'Editing Data with ArcGIS Desktop',
    issuer: 'Esri Certified Training',
    category: 'gis',
    categoryAr: 'نظم معلومات جغرافية',
    date: '2025-02-03',
    year: '2025',
    pdfUrl: './certs/EditingDatawithArcGIS_Desktop.pdf',
    imageUrl: './certs/images/EditingDatawithArcGIS_Desktop.png',
    badgeClass: 'badge-blue',
    description: 'تقنيات التحرير المتقدمة وضبط الجودة والـ Topology في برامج نظم المعلومات الجغرافية Desktop.'
  },
  {
    id: 'cert-essential-workflows-arcgis',
    titleAr: 'أنماط وسير العمل الأساسية في ArcGIS',
    titleEn: 'Essential Workflows in ArcGIS',
    issuer: 'Esri Certified Training',
    category: 'gis',
    categoryAr: 'نظم معلومات جغرافية',
    date: '2025-02-02',
    year: '2025',
    pdfUrl: './certs/EssentialworkflowsInArcGIS.pdf',
    imageUrl: './certs/images/EssentialworkflowsInArcGIS.png',
    badgeClass: 'badge-blue',
    description: 'إتقان استخدام بيئة ArcGIS الاحترافية للتحليل مكاني ورسم الخرائط التفاعلية.'
  },
  {
    id: 'cert-field-data-collection',
    titleAr: 'جمع وإدارة البيانات الميدانية باستخدام تقنيات ArcGIS',
    titleEn: 'Field Data Collection & Management Using ArcGIS',
    issuer: 'Esri Certified Training',
    category: 'gis',
    categoryAr: 'نظم معلومات جغرافية',
    date: '2025-02-01',
    year: '2025',
    pdfUrl: './certs/FieldDataCollection&ManagementUsingArcGIS.pdf',
    imageUrl: './certs/images/FieldDataCollection_ManagementUsingArcGIS.png',
    badgeClass: 'badge-blue',
    description: 'استخدام التطبيقات الميدانية (Field Maps, Survey123) لرفع البيانات الجغرافية ومزامنتها مباشرة مع الغرفة المركزية.'
  },
  {
    id: 'cert-fortiadc-loadbalancer',
    titleAr: 'موازنة الأحمال وحماية التطبيقات FortiADC Load Balancer',
    titleEn: 'FortiADC Load Balancer Technical Certification',
    issuer: 'Fortinet Academy / Network Security',
    category: 'fortinet',
    categoryAr: 'شبكات وأمن سيبراني',
    date: '2025-01-28',
    year: '2025',
    pdfUrl: './certs/FortiADC_LoadBalancer.pdf',
    imageUrl: './certs/images/FortiADC_LoadBalancer.png',
    badgeClass: 'badge-red',
    description: 'توزيع الأحمال وضمان تسريع وأداء التطبيقات ومنع الهجمات الإلكترونية باستخدام أجهزة FortiADC.'
  },
  {
    id: 'cert-fortigate-infrastructure',
    titleAr: 'البنية التحتية وحماية الشبكات FortiGate Infrastructure',
    titleEn: 'FortiGate Infrastructure Security Certification',
    issuer: 'Fortinet Academy',
    category: 'fortinet',
    categoryAr: 'شبكات وأمن سيبراني',
    date: '2025-01-25',
    year: '2025',
    pdfUrl: './certs/FortiGateInfrastructure.pdf',
    imageUrl: './certs/images/FortiGateInfrastructure.png',
    badgeClass: 'badge-red',
    description: 'إدارة الجدران النارية Next-Gen Firewalls وتأمين الاتصالات التشفيرية VPN وإدارة الشبكات المؤسسية.'
  },
  {
    id: 'cert-geodatabase-onjob-training',
    titleAr: 'التدريب العملي الميداني لبناء قواعد البيانات الجغرافية',
    titleEn: 'Geodatabase On-Job Professional Training',
    issuer: 'Geographic Information Systems Training Dept',
    category: 'gis',
    categoryAr: 'نظم معلومات جغرافية',
    date: '2025-01-20',
    year: '2025',
    pdfUrl: './certs/GeoDataBaseOnJobTraining.pdf',
    imageUrl: './certs/images/GeoDataBaseOnJobTraining.png',
    badgeClass: 'badge-blue',
    description: 'التطبيق العملي الميداني والمؤسسي لربط الشبكات والمخططات ببيئة نظم المعلومات الجغرافية.'
  },
  {
    id: 'cert-implement-versioned-workflows',
    titleAr: 'تطبيق سير العمل المتعدد الإصدارات (Versioned Workflows)',
    titleEn: 'Implementing Versioned Workflows in Multiuser Geodatabase',
    issuer: 'Esri Certified Training',
    category: 'gis',
    categoryAr: 'نظم معلومات جغرافية',
    date: '2025-01-15',
    year: '2025',
    pdfUrl: './certs/ImplementVersionedWorkFlowsInMultiuserGeodatabase.pdf',
    imageUrl: './certs/images/ImplementVersionedWorkFlowsInMultiuserGeodatabase.png',
    badgeClass: 'badge-blue',
    description: 'إدارة الإصدارات المتعددة (Versioning) وحل التعارضات في التعديلات المتزامنة لقواعد البيانات الضخمة.'
  },
  {
    id: 'cert-idms-document-management',
    titleAr: 'أنظمة إدارة المستندات والوثائق المتكاملة (IDMS)',
    titleEn: 'Integrated Document Management System (IDMS)',
    issuer: 'Information Technology & Archiving Center',
    category: 'web',
    categoryAr: 'تطوير ويب وإدارة بيانات',
    date: '2025-01-10',
    year: '2025',
    pdfUrl: './certs/IntegratedDocumentManagementSys.pdf',
    imageUrl: './certs/images/IntegratedDocumentManagementSys.png',
    badgeClass: 'badge-green',
    description: 'أرشفة المخططات والمستندات إلكترونياً وربطها بالسجلات الرقمية ونظم المعلومات الجغرافية.'
  },
  {
    id: 'cert-intro-data-reviewer',
    titleAr: 'مراجعة وتدقيق جودة البيانات (ArcGIS Data Reviewer)',
    titleEn: 'Introduction to Data Reviewer for Data Quality',
    issuer: 'Esri Certified Training',
    category: 'gis',
    categoryAr: 'نظم معلومات جغرافية',
    date: '2025-01-05',
    year: '2025',
    pdfUrl: './certs/IntroDataReviewerForDataQuality.pdf',
    imageUrl: './certs/images/IntroDataReviewerForDataQuality.png',
    badgeClass: 'badge-blue',
    description: 'أتمتة الفحص والتدقيق الآلي لسلامة وصحة البيانات المكانية والهندسية قبل إعتمادها.'
  },
  {
    id: 'cert-performing-analysis-arcgis',
    titleAr: 'إجراء التحليلات المكانية المتقدمة في ArcGIS',
    titleEn: 'Performing Analysis in ArcGIS',
    issuer: 'Esri Certified Training',
    category: 'gis',
    categoryAr: 'نظم معلومات جغرافية',
    date: '2024-12-20',
    year: '2024',
    pdfUrl: './certs/PerformingAnalysisInArcGIS.pdf',
    imageUrl: './certs/images/PerformingAnalysisInArcGIS.png',
    badgeClass: 'badge-blue',
    description: 'نمذجة التحليل المكاني واستخراج المؤشرات لدعم متخذي القرار وحل المشكلات الهندسية.'
  },
  {
    id: 'cert-scada-wincc',
    titleAr: 'أنظمة التحكم والمراقبة الصناعية SCADA (Siemens WinCC)',
    titleEn: 'Industrial SCADA Systems (Siemens WinCC)',
    issuer: 'Industrial Automation & SCADA Training Center',
    category: 'scada',
    categoryAr: 'سكادا وأنظمة كهربائية',
    date: '2024-11-15',
    year: '2024',
    pdfUrl: './certs/SCADA(WinCC).pdf',
    imageUrl: './certs/images/SCADA(WinCC).png',
    badgeClass: 'badge-purple',
    description: 'تصميم شاشات التحكم والتفاعل المباشر مع أجهزة PLC ومراقبة شبكات الكهرباء والمحطات لحظياً.'
  },
  {
    id: 'cert-scada-adms',
    titleAr: 'أنظمة إدارة توزيع الكهرباء والسكادا المتقدمة ADMS & SCADA',
    titleEn: 'Advanced Distribution Management Systems (ADMS & SCADA)',
    issuer: 'Electric Power & Smart Grid Center',
    category: 'scada',
    categoryAr: 'سكادا وأنظمة كهربائية',
    date: '2024-10-30',
    year: '2024',
    pdfUrl: './certs/SCADA-ADMS.pdf',
    imageUrl: './certs/images/SCADA-ADMS.png',
    badgeClass: 'badge-purple',
    description: 'الربط المتكامل بين أنظمة المراقبة والتحكم بالشبكة الكهربائية وأنظمة الحسابات الهندسية ADMS.'
  },
  {
    id: 'cert-schematic-sld-generation',
    titleAr: 'توليد المخططات الأحادية والشبكات الكهربائية (SLD Generation)',
    titleEn: 'Schematic Single Line Diagram (SLD) Generation',
    issuer: 'Electrical Engineering & Utilities Dept',
    category: 'scada',
    categoryAr: 'سكادا وأنظمة كهربائية',
    date: '2024-09-15',
    year: '2024',
    pdfUrl: './certs/SchematicSLDgeneration.pdf',
    imageUrl: './certs/images/SchematicSLDgeneration.png',
    badgeClass: 'badge-purple',
    description: 'توليد المخططات الكهربائية الخطية التلقائية من قواعد بيانات GIS وتحليل شبكات القوى.'
  },
  {
    id: 'cert-sharing-gis-content-web',
    titleAr: 'نشر وتشارك المحتوى الجغرافي عبر الويب (Web GIS)',
    titleEn: 'Sharing GIS Content on the Web',
    issuer: 'Esri Certified Training',
    category: 'gis',
    categoryAr: 'نظم معلومات جغرافية',
    date: '2024-08-10',
    year: '2024',
    pdfUrl: './certs/SharingGIS_ContentOnTheWeb.pdf',
    imageUrl: './certs/images/SharingGIS_ContentOnTheWeb.png',
    badgeClass: 'badge-blue',
    description: 'إنشاء الخرائط والتطبيقات التفاعلية على ArcGIS Online و Enterprise Portal وإتاحتها للمستخدمين.'
  },
  {
    id: 'cert-web-developer',
    titleAr: 'تطوير تطبيقات الويب والمنصات التفاعلية (Web Developer)',
    titleEn: 'Full-Stack Web Development Certification',
    issuer: 'Software & Web Development Institute',
    category: 'web',
    categoryAr: 'تطوير ويب وإدارة بيانات',
    date: '2024-06-25',
    year: '2024',
    pdfUrl: './certs/Web-Developer.pdf',
    imageUrl: './certs/images/Web-Developer.png',
    badgeClass: 'badge-green',
    description: 'تطوير المنصات الرقمية المتكاملة باستخدام أحدث تقنيات HTML5, CSS3, JavaScript, APIs والبث المباشر.'
  },
  {
    id: 'cert-arcfm-designer-express',
    titleAr: 'تصميم الشبكات الكهربائية ArcFM Designer Express',
    titleEn: 'ArcFM Designer Express Certification',
    issuer: 'Schneider Electric / ArcFM Suite',
    category: 'gis',
    categoryAr: 'نظم معلومات جغرافية',
    date: '2024-04-12',
    year: '2024',
    pdfUrl: './certs/WorkingwithArcFMDesignerExpress.pdf',
    imageUrl: './certs/images/WorkingwithArcFMDesignerExpress.png',
    badgeClass: 'badge-blue',
    description: 'تخطيط وتصميم المشاريع التوسعية وتكلفة المواد والمعدات الكهربائية على الخرائط الرقمية.'
  },
  {
    id: 'cert-arcfm-electric-advanced',
    titleAr: 'إدارة الشبكات الكهربائية المتقدمة ArcFM Electric & Advanced',
    titleEn: 'Working with ArcFM Electric & Advanced ArcFM',
    issuer: 'Schneider Electric / ArcFM Suite',
    category: 'gis',
    categoryAr: 'نظم معلومات جغرافية',
    date: '2024-03-18',
    year: '2024',
    pdfUrl: './certs/WorkingwithArcFMelectric&AdvancedArcFM.pdf',
    imageUrl: './certs/images/WorkingwithArcFMelectric_AdvancedArcFM.png',
    badgeClass: 'badge-blue',
    description: 'تطبيق نماذج بيانات الطاقة الكهربائية والتغذية التناظرية والتحكم بالطوارئ والأعطال.'
  },
  {
    id: 'cert-arcgis-schematics',
    titleAr: 'التعامل مع المخططات الرسمية التلقائية ArcGIS Schematics',
    titleEn: 'Working with ArcGIS Schematics',
    issuer: 'Esri Certified Training',
    category: 'gis',
    categoryAr: 'نظم معلومات جغرافية',
    date: '2023-11-05',
    year: '2023',
    pdfUrl: './certs/WorkingwithArcGIS_Schematics.pdf',
    imageUrl: './certs/images/WorkingwithArcGIS_Schematics.png',
    badgeClass: 'badge-blue',
    description: 'تحويل الشبكات المعقدة إلى مخططات مبسطة تسهل عملية التتبع والمراقبة الحية.'
  },
  {
    id: 'cert-cad-data-arcgis-desktop',
    titleAr: 'دمج وتبادل بيانات الاوتوكاد CAD في بيئة ArcGIS Desktop',
    titleEn: 'Working with CAD Data in ArcGIS Desktop',
    issuer: 'Esri Certified Training',
    category: 'gis',
    categoryAr: 'نظم معلومات جغرافية',
    date: '2023-08-22',
    year: '2023',
    pdfUrl: './certs/WorkingwithCADdatainArcGIS_DeskTop.pdf',
    imageUrl: './certs/images/WorkingwithCADdatainArcGIS_DeskTop.png',
    badgeClass: 'badge-blue',
    description: 'استيراد وتحويل مخططات AutoCAD / Microstation الجغرافية ودعم نظام الإحداثيات الموحد.'
  },
  {
    id: 'cert-geometric-networks-utilities',
    titleAr: 'إدارة وبناء الشبكات الهندسية للمرافق (Geometric Networks)',
    titleEn: 'Working with Geometric Networks for Utilities',
    issuer: 'Esri Certified Training',
    category: 'gis',
    categoryAr: 'نظم معلومات جغرافية',
    date: '2023-05-14',
    year: '2023',
    pdfUrl: './certs/WorkingwithGeometricNetworksforUtilities.pdf',
    imageUrl: './certs/images/WorkingwithGeometricNetworksforUtilities.png',
    badgeClass: 'badge-blue',
    description: 'نمذجة شبكات المياه والكهرباء والغاز وإجراء تحليلات التتبع والانقطاعات Tracing Analysis.'
  },
  {
    id: 'cert-arcfm-mobile',
    titleAr: 'تطبيقات الهاتف والميدان ArcFM Mobile for Utilities',
    titleEn: 'Working with ArcFM Mobile Suite',
    issuer: 'Schneider Electric / ArcFM Suite',
    category: 'gis',
    categoryAr: 'نظم معلومات جغرافية',
    date: '2023-03-10',
    year: '2023',
    pdfUrl: './certs/WorkwithArcFM_Mobile.pdf',
    imageUrl: './certs/images/WorkwithArcFM_Mobile.png',
    badgeClass: 'badge-blue',
    description: 'تشغيل واستعراض الخرائط التفاعلية بدون إنترنت Offline على الأجهزة الذكية للطواقم الميدانية.'
  },
  {
    id: 'cert-arcfm-web',
    titleAr: 'بوابة الويب الجغرافية المتقدمة ArcFM Web GIS',
    titleEn: 'Working with ArcFM Web Portal',
    issuer: 'Schneider Electric / ArcFM Suite',
    category: 'gis',
    categoryAr: 'نظم معلومات جغرافية',
    date: '2023-01-25',
    year: '2023',
    pdfUrl: './certs/WorkwithArcFMweb.pdf',
    imageUrl: './certs/images/WorkwithArcFMweb.png',
    badgeClass: 'badge-blue',
    description: 'استعراض وتحليل شبكات المرافق عبر الويب باستخدام منصة Geocortex / ArcFM Web.'
  },
  {
    id: 'cert-designing-maps-arcgis',
    titleAr: 'تصميم وإخراج الخرائط الاحترافية (Designing Maps with ArcGIS)',
    titleEn: 'Designing Maps with ArcGIS - Cartography',
    issuer: 'Esri Certified Training',
    category: 'gis',
    categoryAr: 'نظم معلومات جغرافية',
    date: '2022-11-10',
    year: '2022',
    pdfUrl: './certs/DesigningMapsWithArcGIS.jpg',
    imageUrl: './certs/images/DesigningMapsWithArcGIS.png',
    badgeClass: 'badge-blue',
    description: 'إخراج الخرائط التوضيحية وتعديل الرموز والألوان بطرق كارتوجرافية معتمدة وفق المعايير الدولية.'
  }
];

// Helper to get sorted certificates by date
function getCertificatesSortedByDate(order = 'desc') {
  return [...CERTIFICATES_DATA].sort((a, b) => {
    const dateA = new Date(a.date);
    const dateB = new Date(b.date);
    return order === 'desc' ? dateB - dateA : dateA - dateB;
  });
}
