/*(function(){if(window.fetch.toString().indexOf('[native code]')===-1||XMLHttpRequest.prototype.open.toString().indexOf('[native code]')===-1){document.body.innerHTML="";window.location.replace("about:blank");return;}})();*/document.addEventListener("keydown",function(a){"F12"===a.key&&(location.href="/")},!1);
var rmp;
(function(){var PREFIX="/k9x_";function cleanUrl(url){var s=null;if(typeof url==="string"){s=url}else if(typeof URL!=="undefined"&&url instanceof URL){s=url.href}else{return url}if(s.indexOf(PREFIX)===-1)return url;return s.split(PREFIX).join("/")}var originalOpen=XMLHttpRequest.prototype.open;XMLHttpRequest.prototype.open=function(method,url){var args=Array.prototype.slice.call(arguments);args[1]=cleanUrl(url);return originalOpen.apply(this,args)};if(typeof window.fetch==="function"){var originalFetch=window.fetch;window.fetch=function(input,init){if(typeof input==="string"||(typeof URL!=="undefined"&&input instanceof URL)){input=cleanUrl(input)}else if(typeof Request!=="undefined"&&input instanceof Request){var newUrl=cleanUrl(input.url);if(newUrl!==input.url){try{input=new Request(newUrl,input)}catch(e){}}}return originalFetch.call(window,input,init)}}if(typeof navigator!=="undefined"&&typeof navigator.sendBeacon==="function"){var originalBeacon=navigator.sendBeacon;navigator.sendBeacon=function(url,data){return originalBeacon.call(navigator,cleanUrl(url),data)}}})();
var telegramModule={hint:"Join Us on Telegram",svg:"/images/telegram-icon.svg",svgHover:"/images/telegram-icon-hover.svg",callback:function(){if(rmp&&typeof rmp.pause==="function")rmp.pause();window.open("https://t.me/elahmad_tv_apk","_blank","noopener");}};
var jquery_js="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js",mobile_js="https://cdnjs.cloudflare.com/ajax/libs/mobile-detect/1.4.5/mobile-detect.min.js",crypto_js="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.0.0/crypto-js.min.js",video_min_js="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.11.1/video.min.js",videojs_hotkeys_js="https://cdnjs.cloudflare.com/ajax/libs/videojs-hotkeys/0.2.27/videojs.hotkeys.min.js",videojs_fullscreen_js="https://cdn.jsdelivr.net/npm/videojs-landscape-fullscreen@11.1111.0/dist/videojs-landscape-fullscreen.min.js",videojs_pip_js="https://players.brightcove.net/videojs-pip/1/videojs-pip.min.js",videojs_plugin_js="/tv/embed/cloudflare/videojs_plugin.js?v=4.9",videojs_airplay="/tv/embed/cloudflare/plugins/videojs.airplay.js",videojs_hlsjs="https://cdn.streamroot.io/videojs-hlsjs-plugin/1/stable/videojs-hlsjs-plugin.js",cloudflare_css="/tv/embed/cloudflare/cloudflare.css?v=4.9",plyr_css="https://cdnjs.cloudflare.com/ajax/libs/plyr/3.7.8/plyr.min.css",plyr_js="https://cdnjs.cloudflare.com/ajax/libs/plyr/3.7.8/plyr.min.js",mpegts_js="https://xqq.im/mpegts.js/dist/mpegts.js?v=1.7.0",dplayer_js="https://cdnjs.cloudflare.com/ajax/libs/dplayer/1.27.1/DPlayer.min.js";
var isOpera=(!!window.opr&&!!window.opr.addons)||!!window.opera||navigator.userAgent.indexOf(" OPR/")>=0,isIE11=!!window.MSInputMethodContext&&!!document.documentMode,radiant_js=isOpera||isIE11?"/tv/embed/radiant/is/rm.min.js?v=3.4":"/tv/embed/radiant/releases/js/rm.min.js?v=10.7.9";
var RADIANT_LICENSE="Kl8lYWVvPTNla2Nza3YyNzk/cm9tNWRhc2lzMzBkYjBBJV8q";
var ad_blocker='<div style="background-color:rgba(0,0,0,0.5);height:100%;width:100%"><div style="position:absolute;left:10%;width:80%;top:50%;height:auto;color:#fff;font-size:16px;text-align:center;background:#212121;padding:12px;border:1px solid #fff;-webkit-box-shadow:0 3px 8px rgba(0,0,0,.4);-moz-box-shadow:0 3px 8px rgba(0,0,0,.4);box-shadow:0 3px 8px rgba(0,0,0,.4);-webkit-transform:translateY(-50%);-moz-transform:translateY(-50%);transform:translateY(-50%)">Ad-blocker detected. To view this content please disable your ad-blocker.</div></div>';
(function(){if(!Array.prototype.forEach){Array.prototype.forEach=function(fn,thisArg){if(this==null)throw new TypeError("Array.prototype.forEach called on null");var t=Object(this),len=t.length>>>0,i;for(i=0;i<len;i++)if(i in t)fn.call(thisArg,t[i],i,t);};}if(!Array.prototype.indexOf){Array.prototype.indexOf=function(search,fromIndex){var len=this.length>>>0;var i=fromIndex?Number(fromIndex):0;if(i<0)i=Math.max(0,len+i);for(;i<len;i++)if(i in this&&this[i]===search)return i;return-1;};}if(!Array.isArray){Array.isArray=function(a){return Object.prototype.toString.call(a)==="[object Array]";};}if(!Object.keys){Object.keys=function(o){var r=[],k;for(k in o)if(Object.prototype.hasOwnProperty.call(o,k))r.push(k);return r;};}if(!String.prototype.trim){String.prototype.trim=function(){return this.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,"");};}if(!Function.prototype.bind){Function.prototype.bind=function(oThis){var aArgs=Array.prototype.slice.call(arguments,1),fToBind=this;return function(){return fToBind.apply(oThis,aArgs.concat(Array.prototype.slice.call(arguments)));};};}})();
function showError(msg){try{if(window.console&&console.error)console.error(msg);}catch(e){}var p=document.getElementById("player");if(!p)return;p.innerHTML="";var d=document.createElement("div");d.style.cssText="color:white;padding:20px;text-align:center;";if(typeof d.textContent==="string")d.textContent=String(msg);else d.innerText=String(msg);p.appendChild(d);}
function reloadWithLimit(max){max=max||5;try{var key="player_retries:"+location.href;var n=parseInt(sessionStorage.getItem(key),10)||0;if(n>=max){showError("The stream is unavailable right now. Please try again later.");return;}sessionStorage.setItem(key,String(n+1));window.location.reload();}catch(e){showError("Stream error. Please refresh the page.");}}
function clearReloadCounter(){try{sessionStorage.removeItem("player_retries:"+location.href);}catch(e){}}
var config_setup ={xhrSetup: function(xhr, url) {if (url.indexOf("/k9x_") > -1) {url = url.split("k9x_").join("");}xhr.open("GET", url, true);}};
function $_GET(name){var safe=name.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");var m=location.search.match(new RegExp("[?&$]"+safe+"=([^&$]*)"));if(!m){try{if(window.console&&console.warn)console.warn("Query parameter '"+name+"' is missing - using default channel.");}catch(e){}return"alarabiya_alhadath1";}var v=m[1].replace(/\+/g," ");try{return decodeURIComponent(v);}catch(e){return v;}}
var stream=$_GET("id");
var loadedScripts={};
function loadScripts(list,done,fail){var queue=list.slice();(function next(){if(!queue.length){if(done)done();return;}var item=queue.shift();var src=typeof item==="string"?item:item.src;var optional=typeof item==="object"&&item.optional;if(loadedScripts[src]){next();return;}var s=document.createElement("script");s.src=src;s.charset="UTF-8";var finished=false;var timer=setTimeout(function(){if(finished)return;finished=true;s.onload=s.onerror=s.onreadystatechange=null;try{if(window.console&&console.warn)console.warn("Script load timeout: "+src);}catch(e){}if(optional){next();return;}if(fail)fail(src);else showError("Failed to load (timeout): "+src);},35000);s.onreadystatechange=function(){if(s.readyState==="loaded"||s.readyState==="complete"){if(finished)return;finished=true;clearTimeout(timer);s.onload=s.onerror=s.onreadystatechange=null;loadedScripts[src]=true;next();}};s.onload=function(){if(finished)return;finished=true;clearTimeout(timer);s.onload=s.onerror=s.onreadystatechange=null;loadedScripts[src]=true;next();};s.onerror=function(){if(finished)return;finished=true;clearTimeout(timer);s.onload=s.onerror=s.onreadystatechange=null;try{if(window.console&&console.warn)console.warn("Failed to load script: "+src);}catch(e){}if(optional){next();return;}if(fail)fail(src);else showError("Failed to load: "+src);};document.head.appendChild(s);})();}
function load_css(href){if(document.querySelector('link[href="'+href+'"]'))return;var l=document.createElement("link");l.rel="stylesheet";l.type="text/css";l.href=href;l.media="all";document.head.appendChild(l);}
function makeVideo(src,type,opts){opts=opts||{};var v=document.createElement("video");v.id=opts.id||"fcplayer";if(opts.className)v.className=opts.className;if(opts.style)v.style.cssText=opts.style;v.setAttribute("width","100%");v.setAttribute("height","100%");v.setAttribute("playsinline","");v.controls=true;if(opts.autoplay)v.autoplay=true;if(src){var s=document.createElement("source");s.src=src;if(type)s.type=type;v.appendChild(s);}var holder=document.getElementById("player");if(!holder){showError("#player element not found");return v;}holder.appendChild(v);return v;}
function getType(a){if(/\.(mp3|m4a)/i.test(a))return"audio/mpeg";if(/^rtmp:\/\//.test(a))return"rtmp/mp4";if(/\.(php|m3u8)/i.test(a))return"application/x-mpegURL";if(/\.(mp4|m4p|m4v|mov)/i.test(a))return"video/mp4";if(/\.f4m/.test(a))return"application/adobe-f4m";if(/\.mpd/.test(a))return"application/dash+xml";if(/\.flv/.test(a))return"video/flv";if(/\.(webm|mkv)/.test(a))return"video/webm";if(/\.ogg/.test(a))return"video/ogg";if(/(youtu\.be\/|youtube\.com\/(watch\?v=|embed\/|v\/))/.test(a))return"video/youtube";if(/dailymotion\.com/.test(a))return"video/dailymotion";if(/vimeo\.com/.test(a))return"video/vimeo";return"application/x-mpegURL";}
function isMobileUA(){return typeof MobileDetect!=="undefined"&&!!new MobileDetect(navigator.userAgent).mobile();}
var ORIGINAL_TITLE=document.title;
function titlet(a){var tit=String(a).replace(/_/g," ");document.title=ORIGINAL_TITLE+" - "+tit;}
var ref=document.referrer.toLowerCase();
var water_mark=ref.indexOf("elahmad.ru")>-1||ref.indexOf("elahmad.site")>-1?"":"/images/add_elahmad.png";
var zoekstring=document.location.href;
function embedIframeCode(extraAllow){return'<iframe width="560" height="315" src="'+zoekstring+'" style="border:none;" allowfullscreen allow="'+(extraAllow||"autoplay; fullscreen")+'"></iframe>';}
function bindOnce(el,evt,handler){if(!el)return;el.__h=el.__h||{};if(el.__h[evt])el.removeEventListener(evt,el.__h[evt]);el.__h[evt]=handler;el.addEventListener(evt,handler);}
function unsand(){var p=document.getElementById("player");if(!p)return;p.innerHTML='<div style="position:absolute;top:0;left:0;width:100%;height:100%;pointer-events:none"><div style="position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);background-color:#333;color:#fff;padding:20px;border-radius:10px;text-align:center;font-size:16px;z-index:1000;box-shadow:0 4px 8px rgba(0,0,0,0.2)">Remove sandbox attributes on the iframe tag</div></div>';if(window.$)$(document).off("click","*");}
function unsandbox_alt(){setTimeout(function(){var ios=/iPad|iPhone|iPod/.test(navigator.platform)||(navigator.platform==="MacIntel"&&navigator.maxTouchPoints>1);var edge=/Edge/.test(navigator.userAgent);if(!ios&&!edge){var p=document.getElementById("player");if(!p)return;var o=document.createElement("object");o.data="data:application/pdf;base64,aG1t";o.setAttribute("width","1px");o.setAttribute("height","1px");o.style.cssText="position:absolute;top:-500px;left:-500px;visibility:hidden;";o.onerror=function(){unsand();if(o.parentNode)o.parentNode.removeChild(o);};p.appendChild(o);}},10000);}
function unsandbox(){try{var f=window.frameElement;if(f&&f.hasAttribute("sandbox")){var s=f.getAttribute("sandbox");if(s.indexOf("allow-forms")!==-1&&s.indexOf("allow-same-origin")!==-1&&s.indexOf("allow-scripts")!==-1){var p=document.getElementById("player");if(p){var o=document.createElement("div");o.style.cssText="position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,.7);z-index:99999;display:-webkit-box;display:-ms-flexbox;display:flex;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-pack:center;-ms-flex-pack:center;justify-content:center;pointer-events:none;";var m=document.createElement("div");m.style.cssText="position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);-ms-transform:translate(-50%,-50%);background:#333;color:#fff;padding:20px;border-radius:10px;text-align:center;font-size:16px;z-index:100000;box-shadow:0 4px 8px rgba(0,0,0,.2)";if(typeof m.textContent==="string")m.textContent="Remove sandbox attributes on the iframe tag";else m.innerText="Remove sandbox attributes on the iframe tag";o.appendChild(m);p.appendChild(o);}}}}catch(e){}}
function fetchDecryptedStream(id,callback){if(typeof embed_result==="undefined"){showError("Configuration error: embed_result is not defined on the page.");return;}if(typeof CryptoJS==="undefined"){showError("CryptoJS is not loaded. Please refresh the page.");return;}var xhr=new XMLHttpRequest();xhr.open("POST",embed_result,true);xhr.setRequestHeader("Content-Type","application/x-www-form-urlencoded");try{xhr.timeout=30000;}catch(e){}var meta=document.querySelector('meta[name="csrf-token"]');var csrf=meta?meta.getAttribute("content"):"";var done=false;function finish(fn){if(done)return;done=true;fn();}xhr.onreadystatechange=function(){if(xhr.readyState!==4)return;finish(function(){if(xhr.status===0){showError("Network error or timeout. Please try again.");return;}if(xhr.status!==200){showError("Request failed with status: "+xhr.status);return;}var data;try{data=JSON.parse(xhr.responseText);}catch(err){showError("Parsing error: "+err);return;}if(data.error){showError("Error: "+data.error);return;}var url;try{url=my_crypt_new(data.link_4,data.key,data.iv);}catch(err){showError("Decryption error: "+err);return;}if(!url){showError("Could not decrypt the stream link.");return;}callback(url);});};xhr.ontimeout=function(){finish(function(){showError("Request timed out. Please try again.");});};xhr.onerror=function(){finish(function(){showError("Network error while fetching stream.");});};xhr.send("id="+encodeURIComponent(id)+"&csrf_token="+encodeURIComponent(csrf));}
var easyToken="";
var easyPatched=false;
function installEasyBroadcastPatch(){if(easyPatched)return;easyPatched=true;var origOpen=XMLHttpRequest.prototype.open;XMLHttpRequest.prototype.open=function(method,url){var args=Array.prototype.slice.call(arguments);try{if(easyToken&&typeof url==="string"&&url.indexOf("easybroadcast.io")!==-1&&(url.indexOf("playlist_dvr.m3u8")!==-1||url.indexOf("chunks_dvr.m3u8")!==-1)){args[1]=url+(url.indexOf("?")!==-1?"&":"?")+easyToken;}}catch(e){}return origOpen.apply(this,args);};var origFetch=window.fetch;if(typeof origFetch==="function"){window.fetch=function(input,init){try{var u=typeof Request!=="undefined"&&input instanceof Request?input.url:input;if(easyToken&&typeof u==="string"&&u.indexOf("easybroadcast.io")!==-1&&(u.indexOf(".m3u8")!==-1||u.indexOf(".ts")!==-1)){var nu=u+(u.indexOf("?")!==-1?"&":"?")+easyToken;if(input instanceof Request){return origFetch.call(window,new Request(nu,input),init);}return origFetch.call(window,nu,init);}}catch(e){}return origFetch.apply(window,arguments);};}}
function my_crypt_new(g,b,f){var cipher=CryptoJS.enc.Base64.parse(g),key=CryptoJS.enc.Hex.parse(b),iv=CryptoJS.enc.Hex.parse(f);var a=CryptoJS.AES.decrypt({ciphertext:cipher},key,{iv:iv,mode:CryptoJS.mode.CBC,padding:CryptoJS.pad.Pkcs7});var dec=a.toString(CryptoJS.enc.Utf8)||"";var qi=dec.indexOf("?");easyToken=qi!==-1?dec.substring(qi+1):"";if(easyToken)installEasyBroadcastPatch();return dec;}
function my_crypt(a,d,e){d=CryptoJS.enc.Utf8.parse(d);e=CryptoJS.enc.Utf8.parse(e);a=CryptoJS.AES.decrypt(a,d,{iv:e});return CryptoJS.enc.Utf8.stringify(a);}
function someFunction(a,d,e){load_css(cloudflare_css);var video=makeVideo(d,e,{id:"div_player",className:"video-js vjs-default-skin vjs-big-play-centered vjs-16-9 videoCentered",style:"width:100%;height:100%"});video.setAttribute("preload","auto");loadScripts([video_min_js,videojs_plugin_js,{src:videojs_hotkeys_js,optional:true}],function(){if(typeof videojs==="undefined"){showError("video.js failed to load.");return;}videojs.options.liveui=!(videojs.browser.IS_ANDROID||videojs.browser.IS_IOS);videojs("div_player",{controls:true,preload:"auto",width:"100%",height:"100%",sources:[{src:d,type:e}],html5:{nativeAudioTracks:false,nativeVideoTracks:false},fluid:true},function(){var player=this;if(typeof player.elahmad==="function"){player.elahmad({related:[{thumb:"/tv/images/livetv_logo.png",url:"/tv/arabic-live-channels.php",title:"Web tv",duration:""},{thumb:"/tv/images/livetv_logo.png",url:"/tv/mobile-live-stream/",title:"Mobile tv",duration:""}],logo:water_mark,logourl:"https://www.elahmad.ru",logoposition:"RT",rateMenu:false,target:"_blank"});}player.on("playing",clearReloadCounter);player.on("error",function(){setTimeout(function(){reloadWithLimit();},3000);});if(typeof player.hotkeys==="function")player.hotkeys({volumeStep:0.1,seekStep:5,alwaysCaptureHotkeys:true});setTimeout(function(){var p=player.play();if(p&&p.catch)p.catch(function(){});},1000);});});}
function video_js(){fetchDecryptedStream(stream,function(url){someFunction(null,url,getType(url));});}
function videojsUnmutePage(src,cfg){load_css(cfg.css);var type=getType(src);makeVideo(src,type,{id:"fcplayer",className:"video-js vjs-default-skin vjs-big-play-centered videoCentered",style:"position:absolute;left:0;top:0;width:100%;height:100%;",autoplay:true});loadScripts([cfg.videojs,cfg.plugin,{src:videojs_fullscreen_js,optional:true},{src:videojs_hotkeys_js,optional:true},{src:videojs_pip_js,optional:true},{src:mobile_js,optional:true},{src:videojs_airplay,optional:true}],function(){if(typeof videojs==="undefined"){showError("video.js failed to load.");return;}var g=videojs("fcplayer",{controls:true,autoplay:true,preload:"auto",width:"100%",height:"100%",html5:{hls:{overrideNative:true},nativeAudioTracks:false,nativeVideoTracks:false},sources:[{type:type,src:src}]});function unmute(){var btns=document.querySelectorAll(".btn-unmute");Array.prototype.forEach.call(btns,function(el){el.style.display="none";});var p=g.play();if(p&&p.catch)p.catch(function(){});g.muted(false);}g.on("play",unmute);load_css("https://fonts.googleapis.com/icon?family=Material+Icons");var btn=document.createElement("div");btn.className="btn-unmute";btn.style.cssText="text-align:center;background:#222321;z-index:3;color:#fff;position:absolute;top:60px;left:60px;width:200px;border:2px solid #fff;padding:4px 0;border-radius:2px;cursor:pointer;opacity:.8";btn.innerHTML='<div class="unmuteInfo" title="Play Video" id="btn-unmute">CLICK HERE TO UNMUTE <i class="material-icons" style="font-size:48px;color:red">volume_off</i><i class="material-icons" style="font-size:48px;color:red">play_arrow</i></div>';document.body.appendChild(btn);btn.querySelector(".unmuteInfo").onclick=function(){unmute();btn.style.display="none";return false;};if(typeof g.elahmad==="function")g.elahmad({});if(typeof g.airplay==="function")g.airplay();if(typeof g.landscapeFullscreen==="function")g.landscapeFullscreen();if(typeof g.hotkeys==="function")g.hotkeys({volumeStep:0.1,seekStep:5,alwaysCaptureHotkeys:true});if(typeof g.pip==="function")g.pip({allowOnMobile:true});g.on("error",function(){isMobileUA()?mobile_new(src):extension(src);});});}
function load_videojs(a){videojsUnmutePage(a,{css:cloudflare_css,videojs:video_min_js,plugin:videojs_plugin_js});}
function load_videojs_v7(g){videojsUnmutePage(g,{css:"/tv/embed/cloudflare/cloudflare_v7.css?v=v7.0",videojs:"https://cdnjs.cloudflare.com/ajax/libs/video.js/7.10.0/video.min.js",plugin:"/tv/embed/cloudflare/videojs_plugin_v7.js?v=v7.0"});}
function videojs_kw(){fetchDecryptedStream(stream,function(t){videojs_player(t);});}
function videojs_player(t){loadScripts(["/tv/embed/kwikmotion/KwikMotion.js"],function(){if(typeof kwikMotion==="undefined"){showError("KwikMotion failed to load.");return;}kwikMotion("player",{autostart:true,sources:[{file:t}],width:"100%",height:"100%"});},function(src){showError("Failed to load KwikMotion: "+src);});}
function wowza_player(src){function start(){load_css("/tv/embed/cloudflare/cloudflare.css");makeVideo(src,"application/x-mpegURL",{id:"fcplayer",className:"video-js vjs-default-skin vjs-big-play-centered",style:"position:absolute;left:0;top:0;width:100%;height:100%;",autoplay:true});loadScripts([video_min_js,videojs_plugin_js,{src:videojs_fullscreen_js,optional:true}],function(){if(typeof videojs==="undefined"){showError("video.js failed to load.");return;}var p=videojs("fcplayer",function(){});if(typeof p.elahmad==="function")p.elahmad({});if(typeof p.landscapeFullscreen==="function")p.landscapeFullscreen();});}if(document.readyState!=="loading")start();else document.addEventListener("DOMContentLoaded",start);}
function radiant(){fetchDecryptedStream(stream,function(url){radiant_new(url);});}
function radiantSource(u){if(u.indexOf(".ogg")!==-1)return{src:{ogg:u},audioOnly:true};if(u.indexOf(".m4a")!==-1)return{src:{m4a:u},audioOnly:true};if(u.indexOf(".mp3")!==-1)return{src:{mp3:u},audioOnly:true};if(u.indexOf(".webm")!==-1)return{src:{webm:u},audioOnly:false};if(u.indexOf(".m3u8")!==-1||u.indexOf(".php")!==-1)return{src:{hls:u},audioOnly:false};if(u.indexOf(".mpd")!==-1)return{src:{dash:u},audioOnly:false};if(u.indexOf(".ogv")!==-1||u.indexOf(".mkv")!==-1||u.indexOf(".mp4")!==-1)return{src:{mp4:u},audioOnly:false};return{src:{hls:u},audioOnly:false};}
function radiantErrorFallback(u){var ua=navigator.userAgent;function go(){if((typeof MobileDetect!=="undefined"&&new MobileDetect(ua).mobile())||/webOS|Tizen|SmartTV/i.test(ua))mobile_new(u);else setTimeout(function(){extension(u);},500);}loadScripts([mobile_js],go,go);}
function radiant_new(b){loadScripts([radiant_js],function(){if(typeof RadiantMP==="undefined"){showError("RadiantMP failed to load.");return;}var s=radiantSource(b);var positions=["topleft","bottomleft","topright","bottomright"];var cfg={licenseKey:RADIANT_LICENSE,src:s.src,iframeMode:true,iframeAllowed:true,skin:"s1",autoplay:true,pip:true,forceMseHlsOnAppleDevices:true,audioOnly:s.audioOnly,logo:{imgUri:water_mark,clickUri:"https://www.elahmad.ru",position:positions[Math.floor(Math.random()*4)],margin:"8px",watermark:false,pauseContentOnLogoClick:true},sharing:true,sharingUrl:zoekstring,hlsJSCustomConfig:config_setup,sharingNetworks:["facebook","twitter","linkedin","reddit","email"],sharingCode:embedIframeCode("autoplay; fullscreen; picture-in-picture; xr-spatial-tracking; encrypted-media"),customModule:[telegramModule]};rmp=new RadiantMP("player");var el=document.getElementById("player");if(el)bindOnce(el,"error",function(){radiantErrorFallback(b);});rmp.init(cfg);});}
function radiant_new_alt(a){loadScripts([radiant_js],function(){if(typeof RadiantMP==="undefined"){showError("RadiantMP failed to load.");return;}var s=radiantSource(a);var isDvr=a.indexOf("?DVR")>-1||a.indexOf("playlist_dvr.m3u8")>-1||a.indexOf("playlist_DVR.m3u8")>-1;var cfg={customModule:[telegramModule],licenseKey:RADIANT_LICENSE,detectViewerLanguage:false,isLiveDvr:isDvr,iframeMode:true,iframeAllowed:true,sharing:true,sharingUrl:zoekstring,sharingNetworks:["facebook","twitter","linkedin","reddit","email"],sharingCode:embedIframeCode("autoplay; fullscreen; picture-in-picture; xr-spatial-tracking; encrypted-media"),skin:"s1",src:s.src,audioOnly:s.audioOnly,delayToFade:3000,pip:true,logo:water_mark,logoLoc:"https://www.elahmad.ru",logoPosition:"bottom",logoWatermark:"false",autoplay:true,hlsJSMaxBufferSize:0,hlsJSMaxBufferLength:15,hlsJSLiveSyncDuration:5,hlsJSLiveMaxLatencyDuration:Infinity,forceHlsJSOnMacOSIpadOSSafari:true,adBlockerDetection:true,adBlockerDetectedPreventPlayback:true,gaTrackingId:"UA-6843551-1",gaCategory:"E-learning video",gaLabel:"How to start with HTML5 video",gaEvents:"context ready playerstart error adimpression adloadererror aderror".split(" ")};rmp=new RadiantMP("player");var el=document.getElementById("player");if(el){bindOnce(el,"error",function(){radiantErrorFallback(a);});var bitrateSet=false;bindOnce(el,"playing",function(){if(bitrateSet)return;bitrateSet=true;if(rmp&&typeof rmp.setBitrate==="function")rmp.setBitrate(4);});}rmp.init(cfg);});}
function radiant_hls(a){loadScripts(["/tv/embed/radiant/releases/js/rm.min.light.js"],function(){if(typeof RadiantMP==="undefined"){showError("RadiantMP failed to load.");return;}var cfg={licenseKey:RADIANT_LICENSE,src:{hls:a},autoplay:true,iframeMode:true,iframeAllowed:true,isLive:true};var c=new RadiantMP("player");var el=document.getElementById("player");if(el)bindOnce(el,"error",function(){setTimeout(function(){reloadWithLimit();},3000);});c.init(cfg);});}
function clappr(){fetchDecryptedStream(stream,function(url){clappr_new(url);});}
function clappr_new(a){load_css("/tv/embed/clappr/embed.min.css?v=0.24");loadScripts(["https://cdnjs.cloudflare.com/ajax/libs/clappr/0.4.7/clappr.min.js","https://cdnjs.cloudflare.com/ajax/libs/dash-shaka-playback/2.0.5/dash-shaka-playback.js","https://cdn.jsdelivr.net/gh/clappr/clappr-level-selector-plugin@latest/dist/level-selector.min.js","https://cdn.jsdelivr.net/npm/clappr-pip@latest/dist/clappr-pip.min.js"],function(){if(typeof Clappr==="undefined"){showError("Clappr failed to load.");return;}var mime=getType(a);var plugins=[Clappr.HLS];if(typeof LevelSelector!=="undefined")plugins.push(LevelSelector);if(typeof DashShakaPlayback!=="undefined")plugins.push(DashShakaPlayback);if(typeof ClapprPip!=="undefined"){plugins.push(ClapprPip.PipButton);plugins.push(ClapprPip.PipPlugin);}var player=window.clapprPlayer=new Clappr.Player({source:a,maxBufferLength:30,hlsjsConfig:{maxBufferLength:30},playback:{debug:true},disableVideoTagContextMenu:false,parentId:"#player",preload:"auto",autoPlay:true,plugins:plugins,mimeType:mime,language:"pt-en",mediacontrol:{seekbar:"#00f5ff",buttons:"#00f5ff"},width:"100%",height:"100%",events:{onError:function(){extension(a);}}});setTimeout(function(){player.play();},3000);});}
function plyr(a){load_css(plyr_css);var type=getType(a);var container=document.getElementById("player");if(!container)return;container.innerHTML="";var video=makeVideo(a,type,{id:"fcplayer",autoplay:true});var libs=[plyr_js];if(type==="application/x-mpegURL")libs.unshift("https://cdnjs.cloudflare.com/ajax/libs/hls.js/0.14.17/hls.min.js");else if(type==="application/dash+xml")libs.unshift("https://cdn.dashjs.org/latest/dash.all.min.js");loadScripts(libs,function(){if(typeof Plyr==="undefined"){showError("Plyr failed to load.");return;}var options={};var instance;if(type==="application/x-mpegURL"){if(typeof Hls!=="undefined"&&Hls.isSupported()){var hls=new Hls();hls.loadSource(a);hls.attachMedia(video);hls.on(Hls.Events.MANIFEST_PARSED,function(){var q=[];hls.levels.forEach(function(l){if(l.height&&q.indexOf(l.height)===-1)q.push(l.height);});q.sort(function(x,y){return y-x;});if(q.length){options.quality={default:q[0],options:q,forced:true,onChange:function(h){hls.levels.forEach(function(l,i){if(l.height===h)hls.currentLevel=i;});}};}instance=new Plyr(video,options);window.plyrInstance=instance;var pr=video.play();if(pr&&pr.catch)pr.catch(function(){});});hls.on(Hls.Events.ERROR,function(ev,data){if(data&&data.fatal){try{console.error("HLS fatal error:",data);}catch(e){}}});window.hls=hls;}else{instance=new Plyr(video,options);video.src=a;}}else if(type==="application/dash+xml"){if(typeof dashjs==="undefined"){showError("dash.js failed to load.");return;}var dash=dashjs.MediaPlayer().create();dash.initialize(video,a,true);instance=new Plyr(video,options);window.dash=dash;}else{instance=new Plyr(video,options);video.src=a;}if(instance)window.plyrInstance=instance;});}
function plyr_player(){fetchDecryptedStream(stream,function(url){plyr(url);});}
function shaka_player(a){var css="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/4.16.3/controls.min.css";load_css(css);var d=document.getElementById("player");if(!d)return;d.innerHTML="";var e=document.createElement("video");e.id="fcplayer";e.className="videoshaka";e.setAttribute("width","100%");e.setAttribute("height","100%");e.setAttribute("playsinline","");d.appendChild(e);loadScripts(["https://cdnjs.cloudflare.com/ajax/libs/shaka-player/4.16.3/shaka-player.ui.min.js"],function(){if(typeof shaka==="undefined"){showError("Shaka Player failed to load.");return;}shaka.polyfill.installAll();if(!shaka.Player.isBrowserSupported()){showError("This browser is not supported by Shaka Player.");return;}var f;function ready(){var ui=new shaka.ui.Overlay(f,d,e);ui.configure({controlPanelElements:["play_pause","time_and_duration","spacer","mute","volume","fullscreen","overflow_menu"],overflowMenuButtons:["captions","quality","language","picture_in_picture","playback_rate"]});window.player=f;f.load(a).then(function(){e.muted=false;var pr=e.play();if(pr&&pr.catch)pr.catch(function(){e.muted=true;e.play();});}).catch(function(err){try{console.error("Error:",err);}catch(er){}});e.addEventListener("dblclick",function(){var fs=document.fullscreenElement||document.msFullscreenElement||document.webkitFullscreenElement;if(fs){(document.exitFullscreen||document.msExitFullscreen||document.webkitExitFullscreen||function(){}).call(document);}else{(e.requestFullscreen||e.msRequestFullscreen||e.webkitRequestFullscreen||function(){}).call(e);}});}if(typeof shaka.Player.prototype.attach==="function"){f=new shaka.Player();f.attach(e).then(ready);}else{f=new shaka.Player(e);ready();}});}
function shaka_play(){fetchDecryptedStream(stream,function(a){shaka_player(a);});}
function mpegts_no(a){load_css(plyr_css);var type=getType(a);var video=makeVideo(a,type,{id:"fcplayer",className:"videoCentered",autoplay:true});loadScripts([mpegts_js,plyr_js],function(){if(typeof window.mpegts==="undefined"||typeof Plyr==="undefined"){showError("mpegts.js or Plyr failed to load.");return;}if(window.mpegts.getFeatureList().mseLivePlayback){var p=window.mpegts.createPlayer({type:"mse",isLive:true,url:a});p.attachMediaElement(video);p.load();p.play();window.mpegtsInstance=p;new Plyr(video);}});}
function mpegts_dplayer(url){var st=document.createElement("style");st.appendChild(document.createTextNode(".dplayer-menu {display: none !important; }"));(document.head||document.getElementsByTagName("head")[0]).appendChild(st);loadScripts([mpegts_js,dplayer_js],function(){if(typeof DPlayer==="undefined"||typeof window.mpegts==="undefined"){showError("DPlayer or mpegts.js failed to load.");return;}window.dpInstance=new DPlayer({container:document.getElementById("player"),preload:"none",autoplay:true,theme:"#FADFA3",loop:true,hotkey:true,volume:0.9,mutex:false,lang:"en-us",video:{url:url,type:"custom_auto",customType:{custom_auto:function(video){var d=window.mpegtsInstance=window.mpegts.createPlayer({type:"mpegts",url:url});d.attachMediaElement(video);d.load();}}}}).play();});}
function mpegts(url){mpegts_dplayer(url);}
function mpegts_player(){fetchDecryptedStream(stream,function(url){mpegts_dplayer(url);});}
function theoplayer(a){var d=document.createElement("link");d.href="//cdn.theoplayer.com/dash/theoplayer/ui.css";d.rel="stylesheet";document.body.appendChild(d);var e=getType(a);var playerText="<div id='player' style='width:100%;height:100%' class='theoplayer video-js theoplayer-skin'></div>";d=document.createElement("div");d.innerHTML=playerText;(function(f,g){document.getElementById(f).appendChild(g);})("player",d.firstChild);(function(f,g){var h=function(l,k){var m=document.createElement("script");m.src=l;m.onload=m.onreadystatechange=function(){m.onreadystatechange=m.onload=null;k();};(document.getElementsByTagName("head")[0]||document.body).appendChild(m);};(function k(){0!=f.length?h(f.shift(),k):g&&g();})();})(["/tv/embed/theoplayer/new/THEOplayer.js"],function(){if(typeof THEOplayer==="undefined"){showError("THEOplayer failed to load.");return;}var f=document.querySelector(".theoplayer");if(!f){showError("THEOplayer container not found.");return;}var p=window.theoInstance=new THEOplayer.Player(f,{libraryLocation:"/tv/embed/theoplayer/new/",width:"100%",pip:{visibility:.7}});p.source={sources:[{src:a,type:e}]};p.autoplay=true;p.social.items=[{label:"Direct link",src:zoekstring},{label:"Embed",text:'<iframe width="560" height="315" src="'+zoekstring+'" style="border:none;" allowfullscreen allow="autoplay; fullscreen; picture-in-picture; xr-spatial-tracking; encrypted-media"></iframe>'}];});}
function theoplayer_player(){fetchDecryptedStream(stream,function(url){getType(url);theoplayer(url);});}
function bitmovin(){fetchDecryptedStream(stream,function(url){getType(url);bitmovin_player(url);});}
function bitmovin_player(url){var originalOpen=XMLHttpRequest.prototype.open;XMLHttpRequest.prototype.open=function(){var target=arguments[1];if(typeof target==="string"&&target.indexOf("licensing.bitmovin.com")!==-1){arguments[1]="data:text/plain;charset=utf-8;base64,"+btoa(JSON.stringify({status:"granted",message:"There you go."}));}return originalOpen.apply(this,arguments);};loadScripts(["https://cdn.jsdelivr.net/npm/bitmovin-player@7.8.25/bitmovinplayer.min.js"],function(){if(typeof bitmovin==="undefined"||!bitmovin.player){showError("Bitmovin player failed to load.");return;}var sourceConfig;if(url.match(/\.(ogg|m4a|mp3|webm|ogv|mkv|mp4)$/i)){sourceConfig={progressive:url};}else if(url.indexOf(".m3u8")!==-1||url.indexOf(".php")!==-1){sourceConfig={hls:url};}else if(url.indexOf(".ism/manifest")!==-1){sourceConfig={smooth:url};}else if(url.indexOf(".mpd")!==-1){sourceConfig={dash:url};}else{sourceConfig={hls:url};}var config={key:"11d3698c-efdf-42f1-8769-54663995de2b",cast:{enable:false},source:sourceConfig,playback:{autoplay:true,muted:false}};var player=bitmovin.player("player");player.addEventHandler(bitmovin.player.EVENT.ON_PLAYBACK_FINISHED,function(){document.location.reload(true);});player.setup(config).then(function(){try{if(window.console&&console.log)console.log("Bitmovin player initialized successfully.");}catch(e){}}).catch(function(){extension(url);});},function(){alert("Error loading Bitmovin script");});}
function jwSharing(sites){var o={code:encodeURI('<iframe src="'+zoekstring+'" width="560" height="315" frameborder="0" scrolling="no" frameborder="0" marginheight="0" marginwidth="0" style="border:none;" allowfullscreen allow="autoplay; fullscreen"></iframe>'),link:""+zoekstring};if(sites)o.sites=sites;return o;}
function jw7(){fetchDecryptedStream(stream,function(url){jw7player(url);});}
function jw7player(a){loadScripts(["//ssl.p.jwpcdn.com/player/v/7.12.13/jwplayer.js"],function(){if(typeof jwplayer==="undefined"){showError("JW Player 7 failed to load.");return;}var e=jwplayer("player");e.setup({key:"WbtWzGvcRNi6Tk+gtKldIbx+nn6lXZFvKiaO2g==",playlist:[{file:a,type:"hls"}],type:"m3u8",allowfullscreen:true,height:"100%",width:"100%",androidhls:true,hlshtml:true,hls:true,flashplayer:"//ssl.p.jwpcdn.com/player/v/7.12.13/jwplayer.flash.swf",aboutlink:"https://www.elahmad.ru",abouttext:"elahmad.ru",logo:{file:water_mark,link:"https://www.elahmad.ru",hide:true,position:"top-left"},sharing:jwSharing("facebook twitter email pinterest tumblr googleplus reddit linkedin custom".split(" ")),autostart:true});e.on("error",function(){extension(a);});});}
function jw8(){fetchDecryptedStream(stream,function(url){jw8player(url);});}
function jw8_hls(){fetchDecryptedStream(stream,function(url){jw8player_hls(url);});}
function jw8Setup(a,extra){loadScripts(["//ssl.p.jwpcdn.com/player/v/8.40.0/jwplayer.js"],function(){if(typeof jwplayer==="undefined"){showError("JW Player 8 failed to load.");return;}var cfg={key:"QybHxeEatECB7VWGt/y7fw69lOha2N4x3Es4kNK1RhDAmYzB",playlist:[{file:a,type:"hls"}],type:"m3u8",allowfullscreen:true,height:"100%",width:"100%",androidhls:true,hlshtml:true,hls:true,primary:"html5",aboutlink:"https://www.elahmad.ru",abouttext:"elahmad.ru",logo:{file:water_mark,link:"https://www.elahmad.ru",hide:true,position:"top-left"},sharing:jwSharing("facebook twitter email pinterest tumblr googleplus reddit linkedin custom".split(" ")),autostart:true};for(var k in extra)if(Object.prototype.hasOwnProperty.call(extra,k))cfg[k]=extra[k];jwplayer("player").setup(cfg).on("adBlock",function(){var p=document.getElementById("player");if(p)p.innerHTML=ad_blocker;});});}
function jw8player(a){jw8Setup(a,{});}
function jw8player_hls(a){jw8Setup(a,{drm:{}});}
function sldpplayer(){fetchDecryptedStream(stream,function(url){sldp_player(url);});}
function sldp_player(url){loadScripts(["https://softvelum.com/player/releases/sldp-v2.24.0.min.js"],function(){if(typeof SLDP==="undefined"){showError("SLDP failed to load.");return;}SLDP.init({container:"player",stream_url:url,adaptive_bitrate:{initial_rendition:"240p"},autoplay:true,width:"100%",height:"100%"});try{if(window.console&&console.log)console.log("SLDP player initialized with:",url);}catch(e){}});}
function algerie(a){if(typeof $==="undefined"){showError("jQuery not loaded.");return;}$.ajax({type:"POST",url:"/tv/result/algerie_result.php",data:a+"=1",dataType:"json",success:function(d){if(!Array.isArray(d)||d.length<2){showError("Invalid response from algerie_result.");return;}var tv=d[0],rtsp=d[1],type=getType(tv);$.get(rtsp,{},function(f){someFunction(d,tv+f,type);},"html");},error:function(){alert("Error occured");}});}
function itworks(a){if(typeof $==="undefined"){showError("jQuery not loaded.");return;}loadScripts(["/tv/videojs/packages/player.js?v=elahmad_24"],function(){if(typeof elahmad_player==="undefined"){showError("elahmad_player is not defined.");return;}$.ajax({type:"POST",url:"/tv/result/itworks_result.php",data:a+"=1",dataType:"json",success:function(d){elahmad_player("player",{width:"100%",height:"100%",autostart:true,sources:[{file:d[0]}],advertising:{}});},error:function(){alert("Error occured");}});});}
function gini_player(a){loadScripts([jquery_js],function(){if(typeof $==="undefined"){showError("jQuery not loaded.");return;}$.ajax({url:window.location.pathname,type:"POST",dataType:"json",data:a,async:true,beforeSend:function(){$("#player").append('<div id="waiting"></div>');},success:function(d){if(!d||!d.link){showError("No stream link returned.");return;}loadScripts([mobile_js],function(){isMobileUA()?mobile_new(d.link):radiant_new(d.link);});},complete:function(){$("#waiting").hide();},error:function(){alert("Error occured");}});});}
var EXT_A="cjfbmleiaobegagekpmlhmaadepdeedn";
var EXT_B="lcipembjfkmeggpihdpdgnjildgniffl";
function extension(h){try{var abs=h;if(typeof URL==="function"){abs=new URL(h,location.href).href;}else if(h.charAt(0)==="/"){abs=location.protocol+"//"+location.host+h;}if(abs===location.href){showError("Cannot play this stream in the current context.");return;}}catch(e){}function show(hasA,hasB){var d=null;if(hasA)d="chrome-extension://"+EXT_A+"/index.html#"+h;else if(hasB)d="chrome-extension://"+EXT_B+"/player.html#"+h;if(d){var p=document.getElementById("player");if(!p)return;p.innerHTML="";var f=document.createElement("iframe");f.src=d;f.className="videoCentered";f.frameBorder="0";f.scrolling="no";f.style.width="100%";f.style.height="100vh";p.appendChild(f);}else{alert("Para ver este contenido, es necesario instalar HLS Player para Chrome o Edge desde el men\u00fa INFO de esta p\u00e1gina web.\n\n"+"To watch this content, you need to install HLS Player for Chrome or Edge from the INFO menu on this website.");}}function probe(){var found=[false,false],answered=[false,false],finished=false;function finish(){if(finished)return;finished=true;show(found[0],found[1]);}document.body.insertAdjacentHTML("beforeend",'<div class="top"><a id="addo" target="_blank" href="https://chrome.google.com/webstore/detail/reproductor-m3u8-hls-%20-da/'+EXT_B+'" title="Play m3u8 HLS">For this Channel use Chrome Extension: <u>HLS Player m3u8</u> to watch channels</a>'+'<img onclick="this.parentElement.style.display=\'none\'" style="position:absolute;top:10px;right:10px;margin:auto;cursor:pointer" title="Close" src="/images/icon_close_16px.gif" width="25" height="25"/></div>');var ids=[EXT_A,EXT_B];for(var i=0;i<ids.length;i++){(function(id,idx){var f=document.createElement("iframe");f.src="chrome-extension://"+id+"/index.html";f.style.display="none";f.onload=function(){found[idx]=true;answered[idx]=true;if(answered[0]&&answered[1])finish();};f.onerror=function(){found[idx]=false;answered[idx]=true;if(answered[0]&&answered[1])finish();};document.body.appendChild(f);})(ids[i],i);}setTimeout(finish,2500);}var ua=navigator.userAgent;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini|CriOS/i.test(ua)){location.href=h;}else if(/Chrome|Edg/.test(ua)&&/Google Inc/.test(navigator.vendor)){probe();}else{if(ua.indexOf("Firefox")!==-1)alert("Este contenido solo funciona en Chrome o Edge.\n\nThis content only works in Chrome or Edge.");try{top.close();}catch(e){}}}
function extensionBanner(storeId,slug){if(typeof $==="undefined")return;$("body").append('<div class="top"><a id="addo" target="_blank" href="https://chrome.google.com/webstore/detail/'+slug+"/"+storeId+'" title="Play m3u8 HLS">For this Channel use Chrome Extension: <u>HLS Player m3u8</u> to watch channels </a>'+'<img onclick="this.parentElement.style.display=\'none\'" style="position:absolute;top:10px;right:10px;margin:auto;cursor:pointer" title="Close" src="/images/icon_close_16px.gif" width="25" height="25"/></div>');}
function extensionIframe(extId,page,url){var topElements=document.querySelectorAll(".top");Array.prototype.forEach.call(topElements,function(el){el.style.display="none";});var player=document.getElementById("player");if(!player)return;player.innerHTML="";var f=document.createElement("iframe");f.className="videoCentered";f.frameBorder="0";f.scrolling="no";f.setAttribute("allowfullscreen","");f.src="chrome-extension://"+extId+"/"+page+"#"+url;player.appendChild(f);}
function extension_ts(a){loadScripts([jquery_js],function(){if(typeof $==="undefined"){showError("jQuery not loaded.");return;}var d=new Image();$(d).on("load",function(){extension2(a);});$(d).on("error",function(){extension1(a);});d.src="chrome-extension://"+EXT_B+"/icon128.png";});}
function extension1(a){var d=new Image();d.onload=function(){extensionIframe(EXT_A,"index.html",a);};d.onerror=function(){extensionBanner(EXT_A,"native-mpeg-dash-%20-hls-pl");};d.src="chrome-extension://"+EXT_A+"/assets/icon128.png";}
function extension2(a){var d=new Image();d.onload=function(){extensionIframe(EXT_B,"player.html",a);};d.onerror=function(){extensionBanner(EXT_B,"reproductor-m3u8-hls-%20-da");};d.src="chrome-extension://"+EXT_B+"/icon128.png";}
function mobiletv(){fetchDecryptedStream(stream,function(url){var p=document.getElementById("player");if(!p)return;p.innerHTML="";var v=makeVideo(url,getType(url),{id:"video",className:"videoCentered",style:"width:100%;height:100%;",autoplay:true});v.removeAttribute("width");v.removeAttribute("height");});}
function mobile_new(a){var p=document.getElementById("player");if(!p)return;p.innerHTML="";var v=makeVideo(a,getType(a),{id:"mobile_video",className:"videoCentered",style:"position:absolute;left:0;top:0;width:100%;height:100%;",autoplay:true});v.setAttribute("autoplay","");}
function iframe_sandbox(a){if(typeof $==="undefined"){showError("jQuery not loaded.");return;}var f=$('<iframe width="100%" height="100%" scrolling="no" sandbox="allow-forms allow-same-origin allow-scripts" frameborder="0" allowfullscreen="allowfullscreen" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"></iframe>');f.attr("src",a);$("#player").empty().append(f);$("#player").css("visibility","visible");}
function iframe_player(a){if(typeof $==="undefined"){showError("jQuery not loaded.");return;}var $p=$("#player");var w=$p.width(),h=$p.height();a=a.replace("{width}",w).replace("{height}",h);var f=$('<iframe allowfullscreen="true" frameborder="0" scrolling="no" style="width:100%;height:100%" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"></iframe>');f.attr("src",a);$p.html(f).css("visibility","visible");}
function set_Https(b){if(typeof b!=="string")return b;var page=window.location.href;if(page.indexOf("https://")===0&&b.indexOf("http://")===0){try{if(window.console&&console.warn)console.warn("Attempting to upgrade insecure stream URL to HTTPS:",b);}catch(e){}return b.replace("http://","https://");}return b;}
function stopCurrentPlayer(){function safe(fn){try{fn();}catch(e){try{console.warn("stopCurrentPlayer:",e);}catch(er){}}}safe(function(){if(rmp&&typeof rmp.destroy==="function")rmp.destroy();rmp=null;});safe(function(){if(window.hls){window.hls.destroy();window.hls=null;}});safe(function(){if(window.dash){window.dash.reset();window.dash=null;}});safe(function(){if(window.plyrInstance){window.plyrInstance.destroy();window.plyrInstance=null;}});safe(function(){if(window.clapprPlayer){window.clapprPlayer.destroy();window.clapprPlayer=null;}});safe(function(){if(window.theoInstance){window.theoInstance.destroy();window.theoInstance=null;}});safe(function(){if(window.dpInstance){window.dpInstance.destroy();window.dpInstance=null;}});safe(function(){if(window.mpegtsInstance){window.mpegtsInstance.destroy();window.mpegtsInstance=null;}});safe(function(){if(window.player&&typeof window.player.destroy==="function"){window.player.destroy();window.player=null;}});safe(function(){if(window.videojs&&typeof videojs.getPlayers==="function"){var ps=videojs.getPlayers();var keys=Object.keys(ps);for(var i=0;i<keys.length;i++){var k=keys[i];if(ps[k]&&typeof ps[k].dispose==="function")ps[k].dispose();}}});safe(function(){if(window.jwplayer&&document.getElementById("player"))jwplayer("player").remove();});safe(function(){var extra=document.querySelectorAll(".btn-unmute, .top");for(var i=0;i<extra.length;i++)if(extra[i].parentNode)extra[i].parentNode.removeChild(extra[i]);});}
function loadplayer(a){stopCurrentPlayer();loadScripts([jquery_js,mobile_js,crypto_js,"https://www.elahmad.ru/js/add_adds.js?v=455.3"],function(){if(typeof $!=="undefined"){$("head").append('<meta http-equiv="referrer" content="no-referrer"/>');}a(stream);titlet(stream);unsandbox();setTimeout(function(){if(typeof add_adds==="function")add_adds();},1000);},function(failedSrc){if(failedSrc.indexOf("add_adds")!==-1){var p=document.getElementById("player");if(p)p.innerHTML=ad_blocker;}else{showError("Failed to load required script: "+failedSrc);}});}
(function b(){try{(function f(e){if(1!==(""+e/e).length||0===e)(function(){}).constructor("debugger")();else debugger;f(++e)})(0)}catch(d){setTimeout(b,250)}})();